language: c
sudo: false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16 && sleep 3 && export DISPLAY=:1.0"
  - curl -O https://downloads.arduino.cc/arduino-1.6.7-linux64.tar.xz
  - tar xJf arduino-1.6.7-linux64.tar.xz
  - mv arduino-1.6.7 $HOME/arduino_ide
install:
  - $HOME/arduino_ide/arduino --install-library SoftwareWire
  - curl https://github.com/RmMsr/pimoroni_arduino_sn3218/archive/feature-software-wire.zip -L > pimoroni_arduino_sn3218-feature-software-wire.zip
  - unzip -d $HOME/Arduino/libraries pimoroni_arduino_sn3218-feature-software-wire.zip
script:
  - $HOME/arduino_ide/arduino --verify --board arduino:avr:LilyPadUSB arduino/arduino.ino
notifications:
  email:
    on_success: change
    on_failure: change
